// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "gf_cms/internal/logic/admin"
	_ "gf_cms/internal/logic/article"
	_ "gf_cms/internal/logic/auth"
	_ "gf_cms/internal/logic/captcha"
	_ "gf_cms/internal/logic/casbinPolicy"
	_ "gf_cms/internal/logic/channel"
	_ "gf_cms/internal/logic/channelModel"
	_ "gf_cms/internal/logic/menu"
	_ "gf_cms/internal/logic/middleware"
	_ "gf_cms/internal/logic/pageInfo"
	_ "gf_cms/internal/logic/permission"
	_ "gf_cms/internal/logic/recycleBin"
	_ "gf_cms/internal/logic/response"
	_ "gf_cms/internal/logic/role"
	_ "gf_cms/internal/logic/runtime"
	_ "gf_cms/internal/logic/setting"
	_ "gf_cms/internal/logic/upload"
	_ "gf_cms/internal/logic/util"
	_ "gf_cms/internal/logic/viewBindFun"
)
