// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_cms/internal/service/internal/dao/internal"
)

// internalCmsRulePermissionsDao is internal type for wrapping internal DAO implements.
type internalCmsRulePermissionsDao = *internal.CmsRulePermissionsDao

// cmsRulePermissionsDao is the data access object for table cms_rule_permissions.
// You can define custom methods on it to extend its functionality as you wish.
type cmsRulePermissionsDao struct {
	internalCmsRulePermissionsDao
}

var (
	// CmsRulePermissions is globally public accessible object for table cms_rule_permissions operations.
	CmsRulePermissions = cmsRulePermissionsDao{
		internal.NewCmsRulePermissionsDao(),
	}
)

// Fill with you ideas below.
