// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_cms/internal/service/internal/dao/internal"
)

// internalCmsSystemSettingDao is internal type for wrapping internal DAO implements.
type internalCmsSystemSettingDao = *internal.CmsSystemSettingDao

// cmsSystemSettingDao is the data access object for table cms_system_setting.
// You can define custom methods on it to extend its functionality as you wish.
type cmsSystemSettingDao struct {
	internalCmsSystemSettingDao
}

var (
	// CmsSystemSetting is globally public accessible object for table cms_system_setting operations.
	CmsSystemSetting = cmsSystemSettingDao{
		internal.NewCmsSystemSettingDao(),
	}
)

// Fill with you ideas below.
