// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_cms/internal/service/internal/dao/internal"
)

// internalCmsAdminDao is internal type for wrapping internal DAO implements.
type internalCmsAdminDao = *internal.CmsAdminDao

// cmsAdminDao is the data access object for table cms_admin.
// You can define custom methods on it to extend its functionality as you wish.
type cmsAdminDao struct {
	internalCmsAdminDao
}

var (
	// CmsAdmin is globally public accessible object for table cms_admin operations.
	CmsAdmin = cmsAdminDao{
		internal.NewCmsAdminDao(),
	}
)

// Fill with you ideas below.
