// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_cms/internal/service/internal/dao/internal"
)

// internalCmsSystemConfigDao is internal type for wrapping internal DAO implements.
type internalCmsSystemConfigDao = *internal.CmsSystemConfigDao

// cmsSystemConfigDao is the data access object for table cms_system_config.
// You can define custom methods on it to extend its functionality as you wish.
type cmsSystemConfigDao struct {
	internalCmsSystemConfigDao
}

var (
	// CmsSystemConfig is globally public accessible object for table cms_system_config operations.
	CmsSystemConfig = cmsSystemConfigDao{
		internal.NewCmsSystemConfigDao(),
	}
)

// Fill with you ideas below.
