// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/v1/user.proto

package v1

import (
	fmt "fmt"
	math "math"
	entity "practices/injection/app/user/api/entity"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request for creating a user
type CreateReq struct {
	// v: required
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" v:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{0}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Response for user creation
type CreateRes struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRes) Reset()         { *m = CreateRes{} }
func (m *CreateRes) String() string { return proto.CompactTextString(m) }
func (*CreateRes) ProtoMessage()    {}
func (*CreateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{1}
}

func (m *CreateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRes.Unmarshal(m, b)
}
func (m *CreateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRes.Marshal(b, m, deterministic)
}
func (m *CreateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRes.Merge(m, src)
}
func (m *CreateRes) XXX_Size() int {
	return xxx_messageInfo_CreateRes.Size(m)
}
func (m *CreateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRes proto.InternalMessageInfo

func (m *CreateRes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Request for retrieving a single user
type GetOneReq struct {
	// v: required
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" v:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneReq) Reset()         { *m = GetOneReq{} }
func (m *GetOneReq) String() string { return proto.CompactTextString(m) }
func (*GetOneReq) ProtoMessage()    {}
func (*GetOneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{2}
}

func (m *GetOneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneReq.Unmarshal(m, b)
}
func (m *GetOneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneReq.Marshal(b, m, deterministic)
}
func (m *GetOneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneReq.Merge(m, src)
}
func (m *GetOneReq) XXX_Size() int {
	return xxx_messageInfo_GetOneReq.Size(m)
}
func (m *GetOneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneReq proto.InternalMessageInfo

func (m *GetOneReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response for single user retrieval
type GetOneRes struct {
	Data                 *entity.User `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetOneRes) Reset()         { *m = GetOneRes{} }
func (m *GetOneRes) String() string { return proto.CompactTextString(m) }
func (*GetOneRes) ProtoMessage()    {}
func (*GetOneRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{3}
}

func (m *GetOneRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneRes.Unmarshal(m, b)
}
func (m *GetOneRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneRes.Marshal(b, m, deterministic)
}
func (m *GetOneRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneRes.Merge(m, src)
}
func (m *GetOneRes) XXX_Size() int {
	return xxx_messageInfo_GetOneRes.Size(m)
}
func (m *GetOneRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneRes proto.InternalMessageInfo

func (m *GetOneRes) GetData() *entity.User {
	if m != nil {
		return m.Data
	}
	return nil
}

// Request for retrieving a list of users
type GetListReq struct {
	// v:required
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty" v:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListReq) Reset()         { *m = GetListReq{} }
func (m *GetListReq) String() string { return proto.CompactTextString(m) }
func (*GetListReq) ProtoMessage()    {}
func (*GetListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{4}
}

func (m *GetListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListReq.Unmarshal(m, b)
}
func (m *GetListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListReq.Marshal(b, m, deterministic)
}
func (m *GetListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListReq.Merge(m, src)
}
func (m *GetListReq) XXX_Size() int {
	return xxx_messageInfo_GetListReq.Size(m)
}
func (m *GetListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetListReq proto.InternalMessageInfo

func (m *GetListReq) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

// Response for user list retrieval
type GetListRes struct {
	List                 []*entity.User `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetListRes) Reset()         { *m = GetListRes{} }
func (m *GetListRes) String() string { return proto.CompactTextString(m) }
func (*GetListRes) ProtoMessage()    {}
func (*GetListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{5}
}

func (m *GetListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListRes.Unmarshal(m, b)
}
func (m *GetListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListRes.Marshal(b, m, deterministic)
}
func (m *GetListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListRes.Merge(m, src)
}
func (m *GetListRes) XXX_Size() int {
	return xxx_messageInfo_GetListRes.Size(m)
}
func (m *GetListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetListRes proto.InternalMessageInfo

func (m *GetListRes) GetList() []*entity.User {
	if m != nil {
		return m.List
	}
	return nil
}

// Request for deleting a user
type DeleteReq struct {
	// User ID to delete
	// v: min:1#
	// v: Please select the user to be deleted.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" dc:"User ID to delete" v:"min:1#Please select the user to be deleted."`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{6}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response for user deletion
type DeleteRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRes) Reset()         { *m = DeleteRes{} }
func (m *DeleteRes) String() string { return proto.CompactTextString(m) }
func (*DeleteRes) ProtoMessage()    {}
func (*DeleteRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{7}
}

func (m *DeleteRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRes.Unmarshal(m, b)
}
func (m *DeleteRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRes.Marshal(b, m, deterministic)
}
func (m *DeleteRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRes.Merge(m, src)
}
func (m *DeleteRes) XXX_Size() int {
	return xxx_messageInfo_DeleteRes.Size(m)
}
func (m *DeleteRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRes proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateReq)(nil), "user.CreateReq")
	proto.RegisterType((*CreateRes)(nil), "user.CreateRes")
	proto.RegisterType((*GetOneReq)(nil), "user.GetOneReq")
	proto.RegisterType((*GetOneRes)(nil), "user.GetOneRes")
	proto.RegisterType((*GetListReq)(nil), "user.GetListReq")
	proto.RegisterType((*GetListRes)(nil), "user.GetListRes")
	proto.RegisterType((*DeleteReq)(nil), "user.DeleteReq")
	proto.RegisterType((*DeleteRes)(nil), "user.DeleteRes")
}

func init() {
	proto.RegisterFile("user/v1/user.proto", fileDescriptor_6eeaf71090dd90b5)
}

var fileDescriptor_6eeaf71090dd90b5 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0x36, 0x54, 0x32, 0x15, 0xad, 0x7b, 0xaa, 0x29, 0x68, 0xd8, 0x53, 0x0f, 0x9a,
	0xc5, 0xfa, 0x06, 0x2a, 0xf4, 0x22, 0x08, 0x01, 0x2f, 0xde, 0x56, 0x32, 0x87, 0x85, 0x36, 0x8d,
	0x99, 0x51, 0xf0, 0xf1, 0x7c, 0x33, 0x99, 0x4d, 0x9a, 0x94, 0xd5, 0x53, 0x86, 0xf9, 0xfe, 0xfd,
	0xf9, 0x67, 0x26, 0xa0, 0x3e, 0x09, 0x1b, 0xf3, 0x75, 0x67, 0xe4, 0x9b, 0xd7, 0xcd, 0x9e, 0xf7,
	0x2a, 0x96, 0x3a, 0xbd, 0xc0, 0x8a, 0x1d, 0x7f, 0x1f, 0x01, 0x7d, 0x0d, 0xc9, 0x63, 0x83, 0x96,
	0xb1, 0xc0, 0x0f, 0xa5, 0x20, 0xae, 0xec, 0x0e, 0x17, 0x51, 0x16, 0xad, 0x92, 0xc2, 0xd7, 0x7a,
	0x39, 0x08, 0x48, 0x9d, 0xc1, 0xd8, 0x95, 0x1d, 0x1e, 0xbb, 0x52, 0xe0, 0x06, 0xf9, 0xa5, 0xf2,
	0xaf, 0x43, 0x78, 0x3b, 0x40, 0x52, 0x19, 0xc4, 0xa5, 0x65, 0xeb, 0xf1, 0x6c, 0x7d, 0x9a, 0xb7,
	0x49, 0xf2, 0x57, 0xc2, 0xa6, 0xf0, 0x44, 0x5f, 0x01, 0x6c, 0x90, 0x9f, 0x1d, 0xb1, 0x98, 0xcd,
	0x61, 0xe2, 0x4a, 0x5a, 0x44, 0xd9, 0x64, 0x95, 0x14, 0x52, 0xea, 0xfc, 0x88, 0x7b, 0xbf, 0xad,
	0x23, 0xf6, 0x82, 0x3f, 0x7e, 0x42, 0x24, 0xdb, 0x13, 0x6e, 0x91, 0xff, 0xcd, 0x36, 0x1b, 0x20,
	0xad, 0x7f, 0x22, 0x88, 0xe5, 0xa1, 0xba, 0x81, 0x69, 0x3b, 0xab, 0x3a, 0xcf, 0xfd, 0x8e, 0xfa,
	0xd5, 0xa4, 0x41, 0x83, 0xf4, 0x48, 0xd4, 0xed, 0x7c, 0x07, 0x75, 0xbf, 0x8a, 0x34, 0x68, 0x88,
	0xda, 0xc0, 0x49, 0x17, 0x5f, 0xcd, 0x7b, 0xda, 0x4d, 0x9b, 0x86, 0x9d, 0xce, 0xbe, 0x8d, 0x78,
	0xb0, 0xef, 0xa7, 0x49, 0x83, 0x06, 0xe9, 0xd1, 0xc3, 0xf2, 0xed, 0x72, 0x67, 0x5d, 0x65, 0x6c,
	0x5d, 0xfb, 0xf3, 0x1a, 0x5b, 0x3b, 0xd3, 0xfd, 0x08, 0xef, 0x53, 0x7f, 0xeb, 0xfb, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe6, 0xd4, 0xa6, 0x88, 0x1a, 0x02, 0x00, 0x00,
}
