// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_cms/api/backendApi"
)

type (
	IAdList interface {
		Add(ctx context.Context, req *backendApi.AdListAddReq) (out interface{}, err error)
		Edit(ctx context.Context, req *backendApi.AdListEditReq) (out interface{}, err error)
		GetAdInfoById(ctx context.Context, id int) (out interface{}, err error)
	}
)

var (
	localAdList IAdList
)

func AdList() IAdList {
	if localAdList == nil {
		panic("implement not found for interface IAdList, forgot register?")
	}
	return localAdList
}

func RegisterAdList(i IAdList) {
	localAdList = i
}
