// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

type ICasbinPolicy interface {
	ObjBackend() string
	ObjBackendApi() string
	CheckByRoleId(roleId, obj, act string) bool
	CheckByAccountId(AccountId, obj, act string) bool
	AddByRoleId(roleId, obj, act string) bool
	RemoveByRoleId(roleId, obj, act string) bool
}

var localCasbinPolicy ICasbinPolicy

func CasbinPolicy() ICasbinPolicy {
	if localCasbinPolicy == nil {
		panic("implement not found for interface ICasbinPolicy, forgot register?")
	}
	return localCasbinPolicy
}

func RegisterCasbinPolicy(i ICasbinPolicy) {
	localCasbinPolicy = i
}
