// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"gf_cms/internal/model"
)

type IChannel interface {
	Index(ctx context.Context) (out []*model.ChannelBackendApiListItem, err error)
}

var localChannel IChannel

func Channel() IChannel {
	if localChannel == nil {
		panic("implement not found for interface IChannel, forgot register?")
	}
	return localChannel
}

func RegisterChannel(i IChannel) {
	localChannel = i
}
