// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_cms/api/backendApi"
)

type (
	IFriendlyLink interface {
		BackendApiStatus(ctx context.Context, req *backendApi.FriendlyLinkStatusReq) (res interface{}, err error)
		BackendApiAdd(ctx context.Context, req *backendApi.FriendlyLinkAddReq) (res interface{}, err error)
	}
)

var (
	localFriendlyLink IFriendlyLink
)

func FriendlyLink() IFriendlyLink {
	if localFriendlyLink == nil {
		panic("implement not found for interface IFriendlyLink, forgot register?")
	}
	return localFriendlyLink
}

func RegisterFriendlyLink(i IFriendlyLink) {
	localFriendlyLink = i
}
