// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"gf_cms/internal/model"
)

type IMenu interface {
	BackendView() []model.MenuGroups
	BackendApi() []model.MenuGroups
	BackendMyMenu(accountId string) []model.MenuGroups
	BackendMyApi(accountId string) []model.MenuGroups
}

var localMenu IMenu

func Menu() IMenu {
	if localMenu == nil {
		panic("implement not found for interface IMenu, forgot register?")
	}
	return localMenu
}

func RegisterMenu(i IMenu) {
	localMenu = i
}
