// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IPageInfo interface {
		LayUiPageInfo(ctx context.Context, total int64, size int) string
	}
)

var (
	localPageInfo IPageInfo
)

func PageInfo() IPageInfo {
	if localPageInfo == nil {
		panic("implement not found for interface IPageInfo, forgot register?")
	}
	return localPageInfo
}

func RegisterPageInfo(i IPageInfo) {
	localPageInfo = i
}
