// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_cms/internal/model"
	"gf_cms/internal/model/entity"

	"github.com/gogf/gf/v2/database/gdb"
)

type (
	IPermission interface {
		BackendAll() []model.PermissionAllItem
		BackendViewAll() []model.PermissionGroups
		BackendApiAll() []model.PermissionGroups
		BackendMyView(accountId string) []gdb.Value
		BackendMyApi(accountId string) []gdb.Value
		GetAllViewPermissionsArray() []string
		GetAllApiPermissionsArray() []string
		BackendUserViewCan(ctx context.Context, routePermission string) bool
		BackendUserApiCan(ctx context.Context, routePermission string) bool
		BackendGetUserFromSession(ctx context.Context) (out *entity.CmsAdmin, err error)
	}
)

var (
	localPermission IPermission
)

func Permission() IPermission {
	if localPermission == nil {
		panic("implement not found for interface IPermission, forgot register?")
	}
	return localPermission
}

func RegisterPermission(i IPermission) {
	localPermission = i
}
