// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"gf_cms/internal/model"

	"github.com/gogf/gf/v2/database/gdb"
)

type IPermission interface {
	BackendAll() []model.PermissionAllItem
	BackendViewAll() []model.PermissionGroups
	BackendApiAll() []model.PermissionGroups
	BackendMyView(accountId string) []gdb.Value
	BackendMyApi(accountId string) []gdb.Value
	GetAllViewPermissionsArray() []string
	GetAllApiPermissionsArray() []string
}

var localPermission IPermission

func Permission() IPermission {
	if localPermission == nil {
		panic("implement not found for interface IPermission, forgot register?")
	}
	return localPermission
}

func RegisterPermission(i IPermission) {
	localPermission = i
}
