// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_cms/api/backend"
	"gf_cms/internal/model"
)

type (
	IRecycleBin interface {
		ModelArticle(ctx context.Context, req *backend.RecycleBinIndexReq) (out []*model.ChannelBackendApiListItem, err error)
	}
)

var (
	localRecycleBin IRecycleBin
)

func RecycleBin() IRecycleBin {
	if localRecycleBin == nil {
		panic("implement not found for interface IRecycleBin, forgot register?")
	}
	return localRecycleBin
}

func RegisterRecycleBin(i IRecycleBin) {
	localRecycleBin = i
}
