// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IResponse interface {
		SuccessJson(ctx context.Context, code int, message string, data interface{})
		SuccessJsonDefault(ctx context.Context)
		SuccessJsonDefaultMessage(ctx context.Context, message string)
		SuccessCodeDefault() int
		SuccessMessageDefault() string
		View(ctx context.Context, template string, data map[string]interface{}) (err error)
		ErrorTpl(ctx context.Context, code int, message string) (err error)
		Pc404(ctx context.Context)
	}
)

var (
	localResponse IResponse
)

func Response() IResponse {
	if localResponse == nil {
		panic("implement not found for interface IResponse, forgot register?")
	}
	return localResponse
}

func RegisterResponse(i IResponse) {
	localResponse = i
}
