// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"gf_cms/internal/model"

	"github.com/gogf/gf/v2/container/gvar"
)

type IRuntime interface {
	GetCpuInfo() model.Cpu
	GetLoadInfo() model.Load
	GetMemInfo() model.Mem
	GetHostInfo() model.Host
	GetDiskInfo() model.Disk
	GetNetInfo() model.Net
	SetServerStartAt() bool
	GetServerStartAt() *gvar.Var
}

var localRuntime IRuntime

func Runtime() IRuntime {
	if localRuntime == nil {
		panic("implement not found for interface IRuntime, forgot register?")
	}
	return localRuntime
}

func RegisterRuntime(i IRuntime) {
	localRuntime = i
}
