// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"gf_cms/internal/model"
	"net/url"
)

type ISetting interface {
	BackendViewAll() []model.SettingGroups
	Save(forms url.Values) bool
}

var localSetting ISetting

func Setting() ISetting {
	if localSetting == nil {
		panic("implement not found for interface ISetting, forgot register?")
	}
	return localSetting
}

func RegisterSetting(i ISetting) {
	localSetting = i
}
