// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_cms/api/backend"
	"gf_cms/api/backendApi"
	"gf_cms/internal/model/entity"
)

type (
	IShortcut interface {
		BackendIndex(ctx context.Context) (out []*entity.CmsShortcut, err error)
		BackendEdit(ctx context.Context, in *backend.ShortcutEditReq) (out *entity.CmsShortcut, err error)
		BackendApiAdd(ctx context.Context, in *backendApi.ShortcutAddReq) (out interface{}, err error)
		BackendApiEdit(ctx context.Context, in *backendApi.ShortcutEditReq) (out interface{}, err error)
		BackendApiBatchDelete(ctx context.Context, in *backendApi.ShortcutBatchDeleteReq) (out interface{}, err error)
		BackendApiSort(ctx context.Context, in *backendApi.ShortcutSortReq) (out interface{}, err error)
	}
)

var (
	localShortcut IShortcut
)

func Shortcut() IShortcut {
	if localShortcut == nil {
		panic("implement not found for interface IShortcut, forgot register?")
	}
	return localShortcut
}

func RegisterShortcut(i IShortcut) {
	localShortcut = i
}
