// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"time"

	"github.com/gogf/gf/v2/container/gvar"
)

type (
	IUtil interface {
		ProjectName() string
		SystemRoot() string
		BackendPrefix() string
		BackendApiPrefix() string
		BackendGroup() string
		BackendApiGroup() string
		ServerRoot() string
		GetConfig(node string) string
		GetSetting(name string) string
		ClearPublicCache() (*gvar.Var, error)
		ClearSystemSettingCache() (*gvar.Var, error)
		GetLocalIP() (ip string, err error)
		FriendyTimeFormat(TimeCreate time.Time, TimeEnd time.Time) string
	}
)

var (
	localUtil IUtil
)

func Util() IUtil {
	if localUtil == nil {
		panic("implement not found for interface IUtil, forgot register?")
	}
	return localUtil
}

func RegisterUtil(i IUtil) {
	localUtil = i
}
