// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"time"

	"github.com/gogf/gf/v2/container/gvar"
)

type IUtil interface {
	ProjectName() string
	SystemRoot() string
	BackendPrefix() string
	BackendApiPrefix() string
	BackendGroup() string
	BackendApiGroup() string
	GetConfig(node string) string
	ClearPublicCache() (*gvar.Var, error)
	ClearSystemSettingCache() (*gvar.Var, error)
	GetLocalIP() (ip string, err error)
	FriendyTimeFormat(TimeCreate time.Time, TimeEnd time.Time) string
}

var localUtil IUtil

func Util() IUtil {
	if localUtil == nil {
		panic("implement not found for interface IUtil, forgot register?")
	}
	return localUtil
}

func RegisterUtil(i IUtil) {
	localUtil = i
}
