// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

type (
	IViewBindFun interface {
		Register()
		SystemSetting(name string) string
		SystemConfig(name string) string
		BackendUrl(route string) string
		BackendApiUrl(route string) string
		PcApiUrl(route string) string
		MApiUrl(route string) string
	}
)

var (
	localViewBindFun IViewBindFun
)

func ViewBindFun() IViewBindFun {
	if localViewBindFun == nil {
		panic("implement not found for interface IViewBindFun, forgot register?")
	}
	return localViewBindFun
}

func RegisterViewBindFun(i IViewBindFun) {
	localViewBindFun = i
}
