// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_cms/internal/dao/internal"
)

// internalCmsAdDao is internal type for wrapping internal DAO implements.
type internalCmsAdDao = *internal.CmsAdDao

// cmsAdDao is the data access object for table cms_ad.
// You can define custom methods on it to extend its functionality as you wish.
type cmsAdDao struct {
	internalCmsAdDao
}

var (
	// CmsAd is globally public accessible object for table cms_ad operations.
	CmsAd = cmsAdDao{
		internal.NewCmsAdDao(),
	}
)

// Fill with you ideas below.
