// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_cms/internal/dao/internal"
)

// internalCmsShortcutDao is internal type for wrapping internal DAO implements.
type internalCmsShortcutDao = *internal.CmsShortcutDao

// cmsShortcutDao is the data access object for table cms_shortcut.
// You can define custom methods on it to extend its functionality as you wish.
type cmsShortcutDao struct {
	internalCmsShortcutDao
}

var (
	// CmsShortcut is globally public accessible object for table cms_shortcut operations.
	CmsShortcut = cmsShortcutDao{
		internal.NewCmsShortcutDao(),
	}
)

// Fill with you ideas below.
