// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_cms/internal/dao/internal"
)

// internalCmsRoleAccountDao is internal type for wrapping internal DAO implements.
type internalCmsRoleAccountDao = *internal.CmsRoleAccountDao

// cmsRoleAccountDao is the data access object for table cms_role_account.
// You can define custom methods on it to extend its functionality as you wish.
type cmsRoleAccountDao struct {
	internalCmsRoleAccountDao
}

var (
	// CmsRoleAccount is globally public accessible object for table cms_role_account operations.
	CmsRoleAccount = cmsRoleAccountDao{
		internal.NewCmsRoleAccountDao(),
	}
)

// Fill with you ideas below.
