// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_cms/internal/dao/internal"
)

// internalCmsGuestbookDao is internal type for wrapping internal DAO implements.
type internalCmsGuestbookDao = *internal.CmsGuestbookDao

// cmsGuestbookDao is the data access object for table cms_guestbook.
// You can define custom methods on it to extend its functionality as you wish.
type cmsGuestbookDao struct {
	internalCmsGuestbookDao
}

var (
	// CmsGuestbook is globally public accessible object for table cms_guestbook operations.
	CmsGuestbook = cmsGuestbookDao{
		internal.NewCmsGuestbookDao(),
	}
)

// Fill with you ideas below.
