// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_cms/internal/dao/internal"
)

// internalCmsArticleBodyDao is internal type for wrapping internal DAO implements.
type internalCmsArticleBodyDao = *internal.CmsArticleBodyDao

// cmsArticleBodyDao is the data access object for table cms_article_body.
// You can define custom methods on it to extend its functionality as you wish.
type cmsArticleBodyDao struct {
	internalCmsArticleBodyDao
}

var (
	// CmsArticleBody is globally public accessible object for table cms_article_body operations.
	CmsArticleBody = cmsArticleBodyDao{
		internal.NewCmsArticleBodyDao(),
	}
)

// Fill with you ideas below.
