// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_cms/internal/dao/internal"
)

// internalCmsFriendlyLinkDao is internal type for wrapping internal DAO implements.
type internalCmsFriendlyLinkDao = *internal.CmsFriendlyLinkDao

// cmsFriendlyLinkDao is the data access object for table cms_friendly_link.
// You can define custom methods on it to extend its functionality as you wish.
type cmsFriendlyLinkDao struct {
	internalCmsFriendlyLinkDao
}

var (
	// CmsFriendlyLink is globally public accessible object for table cms_friendly_link operations.
	CmsFriendlyLink = cmsFriendlyLinkDao{
		internal.NewCmsFriendlyLinkDao(),
	}
)

// Fill with you ideas below.
