// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_cms/internal/dao/internal"
)

// internalCmsImageDao is internal type for wrapping internal DAO implements.
type internalCmsImageDao = *internal.CmsImageDao

// cmsImageDao is the data access object for table cms_image.
// You can define custom methods on it to extend its functionality as you wish.
type cmsImageDao struct {
	internalCmsImageDao
}

var (
	// CmsImage is globally public accessible object for table cms_image operations.
	CmsImage = cmsImageDao{
		internal.NewCmsImageDao(),
	}
)

// Fill with you ideas below.
