// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_cms/internal/dao/internal"
)

// internalCmsAdChannelDao is internal type for wrapping internal DAO implements.
type internalCmsAdChannelDao = *internal.CmsAdChannelDao

// cmsAdChannelDao is the data access object for table cms_ad_channel.
// You can define custom methods on it to extend its functionality as you wish.
type cmsAdChannelDao struct {
	internalCmsAdChannelDao
}

var (
	// CmsAdChannel is globally public accessible object for table cms_ad_channel operations.
	CmsAdChannel = cmsAdChannelDao{
		internal.NewCmsAdChannelDao(),
	}
)

// Fill with you ideas below.
