// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsSystemSetting is the golang structure of table cms_system_setting for DAO operations like Where/Data.
type CmsSystemSetting struct {
	g.Meta    `orm:"table:cms_system_setting, do:true"`
	Id        interface{} //
	Cid       interface{} // 分类id
	Sort      interface{} // 排序
	Name      interface{} // 名称
	Title     interface{} // 标题
	Value     interface{} // 值
	Type      interface{} // 文本类型
	Remarks   interface{} // 备注
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
