// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsSystemConfigCat is the golang structure of table cms_system_config_cat for DAO operations like Where/Data.
type CmsSystemConfigCat struct {
	g.Meta    `orm:"table:cms_system_config_cat, do:true"`
	Id        interface{} //
	Title     interface{} // 设置的分类名称
	Sort      interface{} // 分类排序
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
