// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsSystemConfigCat is the golang structure for table cms_system_config_cat.
type CmsSystemConfigCat struct {
	Id        uint        `json:"id"        ` //
	Title     string      `json:"title"     ` // 设置的分类名称
	Sort      int         `json:"sort"      ` // 分类排序
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
