// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// CmsChannel is the golang structure for table cms_channel.
type CmsChannel struct {
	Id               uint   `json:"id"               ` // 频道ID
	Pid              int    `json:"pid"              ` // 父级ID
	Level            int    `json:"level"            ` // 分类层次
	Name             string `json:"name"             ` // 名称
	Thumb            string `json:"thumb"            ` // 缩略图
	Sort             int    `json:"sort"             ` // 排名
	Status           int    `json:"status"           ` // 状态(0:停用;1:启用;)
	Type             int    `json:"type"             ` // 类型(1:频道;2:单页;3:链接)
	LinkUrl          string `json:"linkUrl"          ` // 链接地址
	LinkTrigger      int    `json:"linkTrigger"      ` // 链接打开方式(0:当前窗口打开;1:新窗口打开;)
	ListController   string `json:"listController"   ` // 列表页控制器
	DetailController string `json:"detailController" ` // 详情页控制器
	ListTemplate     string `json:"listTemplate"     ` // 列表页模板
	DetailTemplate   string `json:"detailTemplate"   ` // 详情页模板
	Description      string `json:"description"      ` // 频道描述
	Model            string `json:"model"            ` // 模型
}
