// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// CmsRoleAccount is the golang structure for table cms_role_account.
type CmsRoleAccount struct {
	AccountId uint `json:"accountId" ` // 账户id
	RoleId    uint `json:"roleId"    ` // 角色id
}
