// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// CmsRoleAccount is the golang structure for table cms_role_account.
type CmsRoleAccount struct {
	Id        uint64 `json:"id"        ` // ID
	AccountId uint64 `json:"accountId" ` // 账户id
	RoleId    uint   `json:"roleId"    ` // 角色id
}
