// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CmsSystemConfigDao is the data access object for table cms_system_config.
type CmsSystemConfigDao struct {
	table   string                 // table is the underlying table name of the DAO.
	group   string                 // group is the database configuration group name of current DAO.
	columns CmsSystemConfigColumns // columns contains all the column names of Table for convenient usage.
}

// CmsSystemConfigColumns defines and stores column names for table cms_system_config.
type CmsSystemConfigColumns struct {
	Id        string //
	Cid       string // 分类id
	Sort      string // 排序
	Name      string // 名称
	Title     string // 标题
	Value     string // 值
	Type      string // 文本类型
	Remarks   string // 备注
	CreatedAt string //
	UpdatedAt string //
}

//  cmsSystemConfigColumns holds the columns for table cms_system_config.
var cmsSystemConfigColumns = CmsSystemConfigColumns{
	Id:        "id",
	Cid:       "cid",
	Sort:      "sort",
	Name:      "name",
	Title:     "title",
	Value:     "value",
	Type:      "type",
	Remarks:   "remarks",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewCmsSystemConfigDao creates and returns a new DAO object for table data access.
func NewCmsSystemConfigDao() *CmsSystemConfigDao {
	return &CmsSystemConfigDao{
		group:   "default",
		table:   "cms_system_config",
		columns: cmsSystemConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CmsSystemConfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CmsSystemConfigDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CmsSystemConfigDao) Columns() CmsSystemConfigColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CmsSystemConfigDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CmsSystemConfigDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CmsSystemConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
