// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CmsSystemConfigCatDao is the data access object for table cms_system_config_cat.
type CmsSystemConfigCatDao struct {
	table   string                    // table is the underlying table name of the DAO.
	group   string                    // group is the database configuration group name of current DAO.
	columns CmsSystemConfigCatColumns // columns contains all the column names of Table for convenient usage.
}

// CmsSystemConfigCatColumns defines and stores column names for table cms_system_config_cat.
type CmsSystemConfigCatColumns struct {
	Id        string //
	Title     string // 设置的分类名称
	Sort      string // 分类排序
	CreatedAt string //
	UpdatedAt string //
}

//  cmsSystemConfigCatColumns holds the columns for table cms_system_config_cat.
var cmsSystemConfigCatColumns = CmsSystemConfigCatColumns{
	Id:        "id",
	Title:     "title",
	Sort:      "sort",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewCmsSystemConfigCatDao creates and returns a new DAO object for table data access.
func NewCmsSystemConfigCatDao() *CmsSystemConfigCatDao {
	return &CmsSystemConfigCatDao{
		group:   "default",
		table:   "cms_system_config_cat",
		columns: cmsSystemConfigCatColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CmsSystemConfigCatDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CmsSystemConfigCatDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CmsSystemConfigCatDao) Columns() CmsSystemConfigCatColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CmsSystemConfigCatDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CmsSystemConfigCatDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CmsSystemConfigCatDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
